#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# Invoke this script to build BetterPushback for both Windows and Linux,
# 32- & 64-bit flavors. Install the necessary mingw cross-compile utilities
# first.
# On Linux also do "apt install libopenal-dev:x86_64 libopenal-dev:i386".

# Locate libacfutils and build it if necessary
LIBACFUTILS="$(qmake -query LIBACFUTILS)"
HOST_OS="$(uname)"
STRIP="strip"

release_dir="debug"
output_dir="output"

if [ "$LIBACFUTILS" = "**Unknown**" ]; then
	echo "Please use \"qmake -set LIBACFUTILS <<path>>\" to " \
	    "point to where you have libacfutils unpacked." >&2
	exit 1
fi

rm -rf "$release_dir" "$output_dir"
mkdir -p "$release_dir" "$output_dir"/{win,mac,lin}_x64

if [[ "$HOST_OS" = "Darwin" ]]; then
	make distclean > /dev/null
	qmake -spec macx-clang && \
	    make -j $NCPUS &&
	    mv libmac.xpl.dylib "$output_dir/mac_x64/OpenWXR.xpl"
	if [ $? != 0 ] ; then
		exit 1
	fi
else
	make distclean > /dev/null
	qmake -set CROSS_COMPILE x86_64-w64-mingw32- && \
	    qmake -spec win32-g++ && \
	    make -j $NCPUS && \
	    mv "$release_dir/win.xpl1.dll" "$output_dir/win_x64/OpenWXR.xpl" \
	    && \
	    "$LIBACFUTILS/tools/mksyms" "$output_dir/win_x64/OpenWXR.xpl" > \
	    "$output_dir/win_x64/syms.txt"
	if [ $? != 0 ] ; then
		exit 1
	fi

	make distclean > /dev/null

	qmake -spec linux-g++-64 && \
	    make -j $NCPUS && \
	    mv liblin.xpl.so "$output_dir/lin_x64/OpenWXR.xpl"
	if [ $? != 0 ] ; then
		exit 1
	fi
fi

make distclean > /dev/null
